microrl: add configuration option for prompt coloring
dimmykar/microrl-remaster pull request #7
Opened 2024-04-15 19:45 UTC by iperry

Add a configuration option for disabling output of ANSI color escape codes. This option is defaulted off to match existing behavior.

2024-04-16 17:52 UTC, dimmykar requested changes
Hello!) Thank you for your contribution to the project.

Yes, this config can really be useful for some developers. I would like to ask you to

1. Squash your commit with the changes I suggested
2. Add note to the changelog about the new config

After that I will merge your request and release new version with this feature

2024-04-16 17:52 UTC, dimmykar commented on src/microrl/microrl.c
> +#endif
```suggestion
#if MICRORL_CFG_USE_PROMPT_COLOR
    mrl->out_fn(mrl, MICRORL_CFG_PROMPT_COLOR);
    mrl->out_fn(mrl, mrl->prompt_ptr);
    mrl->out_fn(mrl, MICRORL_COLOR_DEFAULT);
#else
    mrl->out_fn(mrl, mrl->prompt_ptr);
#endif
```

2024-04-16 17:52 UTC, dimmykar commented on src/include/microrl/microrl_config.h
> + * \brief           Enable ANSI color escape sequences
```suggestion
 * \brief           Enable ANSI color escape sequences in prompt
```

2024-04-17 17:50 UTC, iperry commented
> Hello!) Thank you for your contribution to the project.
> 
> Yes, this config can really be useful for some developers. I would like to ask you to
> 
> 1. Squash your commit with the changes I suggested
> 2. Add note to the changelog about the new config
> 
> After that I will merge your request and release new version with this feature

Thanks. I think I've made the requested modifications, let me know if not.

2024-04-17 18:35 UTC, dimmykar approved these changes
Now all looks good!) Thanks for your contribution!

I will publish `v2.5.0` release in a while

2024-04-17 18:35 UTC, merged